### ISSUE TITLE
AudioStreamPlayer node not found

### ISSUE THREAD

**Issue by JBingrun** [kyzfrintin/Godot-Mixing-Desk#18]
Hi, Thanks for making this amazing add-on!
I watched your tutorial and it is not working when I try to play the song through the code.
Godot keeps telling me that can't find the AudioStreamPlayer node when I init the song by its name.
Do I miss something?

<details><summary>Screenshot</summary>

![](https://upload.cc/i1/2021/01/14/NDUBi7.png)

</details>

**Comment by MJacred** [comment]
Hi!
You are giving it the name of the TRACK (also sometimes called "layer" in the documentation). The name of your song is "pulsar_a".
And in your case, you can use `quickplay("pulsar_a")`, this calls `init_song` and `play` internally

**Comment by kyzfrintin** [comment]
Hi @JBingrun, sorry for the wait, just got back into development on Mixing Desk. @MJacred is quite right, the name passed into the function must be the name of the song, not the name of the individual track inside the containers. But I guess my documentation isn't completely clear, I ought to fix that. And yes, quickplay is recommended, unless you want to initialise your song some time before playing it.
