### ISSUE TITLE
Cannot load plugin due to syntax error, probably in mixing_desk_music.gd

### ISSUE THREAD

**Issue by Mrjcowman** [kyzfrintin/Godot-Mixing-Desk#19]
As far as I can tell from a cursory search, there is supposed to be an argument passed to "stop()" on line 432 of mixing_desk_music.gd... I would assume you're trying to stop the current song, but I'm not entirely certain so I haven't made any changes or pull requests.

As it is now, I can't try out the plugin because Godot won't let me enable it with syntax errors in its scripts. Hopefully that's the culprit?

**Comment by kyzfrintin** [comment]
Just checked in the script and you're right, the arg is missing. Latest push should resolve this.
