### ISSUE TITLE
Needs a demo project

### ISSUE THREAD

**Issue by youreperfect** [kyzfrintin/Godot-Mixing-Desk#3]
This seems like a really nice plugin but its a bit difficut to figure out from the documentation how to actually use the different features and what does what (maybe its more intuitive to audio engineers?)

Can this do basic crossfading of two songs? It feels like it probably can but I can't tell from the docs or looking at the code.

**Comment by kyzfrintin** [comment]
It can indeed crossfade between two songs, by using either the queue_beat/bar functions or through fading them as they play concurrently using fade_in/out respectively. There is a demo project here:

https://github.com/kyzfrintin/Godot-Mixing-Desk-Test-Project

But I will certainly admit it doesn't explain much by itself. I plan to make a series of tutorials to explain features in a clearer manner.

**Comment by kyzfrintin** [comment]
I've started a tutorial series on the Mixing Desk, and the projects used for them are available here:
https://github.com/kyzfrintin/Godot-MDM-Tutorial-Projects

Hopefully this helps.
