### ISSUE TITLE
Script inherits from native type 'Node2D', so it can't be instanced in object of type: 'Spatial

### ISSUE THREAD

**Issue by Michaaaaaaaa** [kyzfrintin/Godot-Mixing-Desk#4]
Very nice plugin, thank you! I have a hard getting it to work properly, though -.- 

When i create a Node of type "RandSoundContainer3D" (notice the "3D" in there), i get an error saying:
> Script inherits from native type 'Node2D', so it can't be instanced in object of type: 'Spatial'

Any idea, what went wrong?
Thank you, 
Micha

**Comment by kyzfrintin** [comment]
For some reason, I slipped up and made the 3D container a child of Node2D rather than a child of Spatial. Sorry for the confusion! It's been fixed a while, I just haven't been on GitHub, so sorry for the late reply.

Hope this helps!
