### ISSUE TITLE
I plan on using your addon. Thanks!

### ISSUE THREAD

**Issue by alex-evelyn** [kyzfrintin/Godot-Mixing-Desk#5]
I couldn't find you on Discord (as Discord said your account didn't exist when I searched for it). I also couldn't figure out how to private message you on Github.

What I want to tell you is that I plan on using Mixing Desk in my [game](https://github.com/alex-evelyn/Sweet-Tea). This is because it is too much of a hassle to get SonicPi to work in Godot. I appreciate your work.

Also, are there working examples of how to use your addon? I keep getting errors when trying to create a test sound (Random Scatter). I already fixed the spaces where tabs should be issue (on my copy of the addon), so that is not the issue.

Edit: Nevermind about the working example, I found your [demo project](https://github.com/kyzfrintin/Godot-Mixing-Desk-Test-Project).

**Comment by kyzfrintin** [comment]
Hey man, awesome to hear you're interested in Mixing Desk! 
Maybe it's the capital "I" throwing it off. I realise now my discord username ![starts with a lowercase "i", ha.](https://i.imgur.com/wfHaiDL.png)

By the way, that demo project is a little out of date. If you want some pointers, then feel free to message me on Discord. I hope the correction helps. And good luck with your game :)
