### ISSUE TITLE
Addon cannot be activated 

### ISSUE THREAD

**Issue by aleksfadini** [kyzfrintin/Godot-Mixing-Desk#7]
Due to a typo on line 24 of mixing_desk.gd

Preloading “sound/2D/multi_sound.gd” throws an error because 2D should be lowercase, 2d. 

Will submit a merge later if this doesn’t get fixed already.

**Comment by kyzfrintin** [comment]
Thank you for pointing this out. Fixing in my next update. Surprised this slipped past me!

**Comment by kyzfrintin** [comment]
#
