### ISSUE TITLE
typo in func _get_ransnd

### ISSUE THREAD

**Issue by fluentmagic** [kyzfrintin/Godot-Mixing-Desk#8]
Hello!

It seems that around line 50 in several of the files (ran_cont.gd in 2D and 3D folders), 
var chance = randi() % children - 1
should be
var chance = randi() % (children - 1)

It makes the script crash otherwise.

Thank you very much for this addon, it's very useful :)

**Comment by kyzfrintin** [comment]
Just added that little fix now. Thanks for pointing this out :)
