### ISSUE TITLE
Song does not loop

### ISSUE THREAD

**Issue by CawawaC** [kyzfrintin/Godot-Mixing-Desk#9]
Hi @kyzfrintin !
First of all, thank you for this, it looks amazing! And might save my life on one or two rhythm game projects I'm currently working on.

But there's one essential thing I can't get to work, although I followed all the instructions: I can't make a song loop. The MDM node is set to loop, points to the song (all the rhythmical values are set correctly), which plays, but then doesn't loop. I only put a core container in there. Is there something I'm missing?
I also noticed that previous versions of GDM had a loop property on the song node, which I don't see in the current version.

**Comment by kyzfrintin** [comment]
Have you set the Play_Mode in the Mixing Desk to `loop_one`?

**Comment by CawawaC** [comment]
I've tried all the play modes on the mixing desk node, but sadly none make it loop.

**Comment by CawawaC** [comment]
I figured it out: I actually was using the GMD from the Godot asset store, which turned out to be version 2.9.3, and not the latest! I apologise for the useless issue.
One other thing though: I'm using Godot 3.1.2, and `AudioServer.bus_count` does not work. Replacing it with `AudioServer.get_bus_count()` seems to do the trick.

**Comment by kyzfrintin** [comment]
Thank you for bringing this to my attention. I admit I have been lax about updating it on the asset store. I should fix that right away. And perhaps I may create a branch for Godot 3.1 that uses the other bus count method. Glad you solved it!
